### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by salewis38** [britkat1980/giv_tcp#101]
Enabling pylint on salewis38 branch of GivTCP repository flags a large number of code issues. Many are down to non-standard Python coding, some may be more serious bugs.
Suggest reviewing and updating once the 2.3 branch is stable (happy to help!).

**Comment by britkat1980** [comment]
Thanks, I'll add the pylint workflow in to my dev branch and work through it (not done this before, so will probably call on your support!)
