### ISSUE TITLE
/enableDischarge not working on Gen2?

### ISSUE THREAD

**Issue by swinbsp** [britkat1980/giv_tcp#110]
My inverter has just been upgraded from a Gen1 to Gen2. Somewhere in the process my ability to pause discharge has been lost.
Is there any known issue with the "enableDischarge" command?
I am accessing this via rest url

I am working around this by changing the discharge rate, so I know my connected etc are all ok

**Comment by yavinmaster** [comment]
I have to admit, I have seen the same issue on my Gen2 but as I hadn't had time to investigate the issue, I hadn't reported it.  I am accessing it via HomeAssistant and MQTT.
