### ISSUE TITLE
EPS Countdown? 

### ISSUE THREAD

**Issue by dbrb2** [britkat1980/giv_tcp#118]
Speaking to GE, a setting had been changed as part of a firmware update that caused me problems with my setup. The support desk were very helpful, and reverted it, which was then tested and found to be working: 

2023-09-27 00:21:29 ! GivEnergy | Enable 0 Second EPS Countdown | Written Successfully 

However, looking through the givTCP MQTT entries I couldn't see this setting. Is it something it is possible to read, so that I can check whether it accidentally gets changed again?

**Comment by britkat1980** [comment]
I can add this to the backlog, provided it’s a “safe” register and it won’t cause any potential to damage the inverter.  I assume it’s fine but will check with GE
