### ISSUE TITLE
When I set a charge the Soc is increased to 100

### ISSUE THREAD

**Issue by chrisf185** [britkat1980/giv_tcp#120]
I am having an odd issue and I can’t track it down.

in a nutshell, the SoC jumps to 100% when I start a force charge for 180 minutes.

I am using the SoC prediction inGivTCP, which appears to set the SoC sometime after midnight. 

I am then running an automation that is looking for the lowest cost on the Agile tariff to perform a charge during the cheapest 3 hour window, it then calls the force Charge, then it starts, but it always charges to 100%.

What I have noticed is the SoC is changed to 100% at the same time I enable the force charge.

I have a second automation that is looking to see when the Power SoC is above the Target SoC to then send the cancel option on the force charge, but because the SoC is set to 100 this doesn’t activate.

Am I using Force Charge correctly?  Or is there another model should be using?  Does force charge change the SoC to 100?

thanks

**Comment by britkat1980** [comment]
ForceCharge is intended to set charge target to 100% to ensure the charge will run for the full time. It will restore the charge target when the ForceCharge concludes.
If you want to set a charge without modifying the target then I suggest setting a charge schedule for the times you need
