### ISSUE TITLE
Force Charge service

### ISSUE THREAD

**Issue by sjs-1956** [britkat1980/giv_tcp#142]
At the moment the sections maximum is 180 mins. Can this be increased to 360 as my batteries take nearly 6 hours to charge if I want to go to 100%?

**Comment by sjs-1956** [comment]
Any thoughts/comments on this request?

**Comment by anthonyangel** [comment]
The force charge service has an option for `Running`, which I assumed would trigger an indefinite force charge, but it appears to do nothing.

![image](https://github.com/britkat1980/giv_tcp/assets/2271981/881338c8-7ec0-4eb0-b92d-d01e44857920)

**Comment by gcoan** [comment]
> The force charge service has an option for `Running`, which I assumed would trigger an indefinite force charge, but it appears to do nothing.
> 
> 
> 
> ![image](https://github.com/britkat1980/giv_tcp/assets/2271981/881338c8-7ec0-4eb0-b92d-d01e44857920)
> 
> 

I set the entity to Running and it works fine for me, but I set charge start time to 00:00:00 and charge end time to 23:59:00 beforehand

**Comment by CaptSB** [comment]
Indeed, you need to be within the period of Time Slot 1 for it to work by
just setting it to Running.
