### ISSUE TITLE
Battery total charge and total discharge shows as 0 on AIO

### ISSUE THREAD

**Issue by blastehh** [britkat1980/giv_tcp#149]
Since I had to set the number of batteries to 0 to get GivTCP to work with my AIO, I'm wondering if this line is causing it to ignore the charge/discharge totals?
https://github.com/britkat1980/giv_tcp/blob/41af5bfdbfde305cfdd74e5f1b8a0cbcdd4ada47/GivTCP/read.py#L271

**Comment by blastehh** [comment]
Actually the code might be unrelated, is the AIO just reporting 0 for battery charge/discharge totals?

**Comment by britkat1980** [comment]
There are two different locations for battery charge and discharge in the registers. It might be that AIO (and presumeably all other HV batteries) have a third location. I'll look into the modbus docs and see what I can find
