### ISSUE TITLE
PALM_ errors appearing in supervisor logs

### ISSUE THREAD

**Issue by naltsta** [britkat1980/giv_tcp#155]
23-12-05 20:42:15 WARNING (MainThread) [supervisor.addons.options] Option 'PALM_CHARGE_RATE' does not exist in the schema for GivTCP (a6a2857d_givtcp)
23-12-05 20:42:15 WARNING (MainThread) [supervisor.addons.options] Option 'PALM_BATT_CAPACITY' does not exist in the schema for GivTCP (a6a2857d_givtcp)

about every 2 minutes

**Comment by britkat1980** [comment]
What version of GivTCP is this in?

**Comment by naltsta** [comment]
2.4.3 running as an add-on on HAOS on a pi3
