### ISSUE TITLE
Set Inverter time from home assistant

### ISSUE THREAD

**Issue by alfwro13** [britkat1980/giv_tcp#156]
I am using GivTCP setup as add-on in Home Assistant. Is there a way to setup inverter time from home assistant?

**Comment by britkat1980** [comment]
Yes, use the MQTT Publish service and send the time you want to set in format '12/11/2021 09:15:32' to topic: "GivEnergy/control/SERIALNUMBER/setDateTime"

**Comment by alfwro13** [comment]
perfect, thank you
