### ISSUE TITLE
Updated giv 2 inverter to D0.912-A0.912 now sensors wont work

### ISSUE THREAD

**Issue by adrianapel** [britkat1980/giv_tcp#158]
Hi, I've updated my inverter firmware and since then givtcp doesn't seem to communicate with the inverter correctly. It is saying 80% of the sensors are now not used, which is all the pv sensors???

Is this a known fault? It's the givenergy local in ha which is struggling to connect, it was working fine before.

I trued uninstalling givtcp and redoing it and it then picks up the 12 sensors only??
![Screenshot_20231214_215214_Chrome](https://github.com/britkat1980/giv_tcp/assets/25438779/6b4331fd-5946-4e88-9fee-2dd07902556a)
![Screenshot_20231214_214819_Chrome](https://github.com/britkat1980/giv_tcp/assets/25438779/c8418549-9aea-4a14-8280-4265d77a8b98)

**Comment by britkat1980** [comment]
If you're using the givenergy local integration (via HACS) then that's a different thing. This is GivTCP, which runs via an addon. I don't think givenergy local works with new firmware inverters. You're welcome to try GivTCP, it should be compatible with all GE kit.
