### ISSUE TITLE
Add battery charge percentage controls

### ISSUE THREAD

**Issue by JRascagneres** [britkat1980/giv_tcp#178]
Can we get these added to GivTCP please?

![image](https://github.com/britkat1980/giv_tcp/assets/3264971/d50a0793-287a-446d-80b8-70260c2a91a5)

**Comment by Adrian57** [comment]
They are already there: 
givtcp_sa999999999_battery_discharge_rate
givtcp_sa99999999_battery_charge_rate

Cheers

**Comment by britkat1980** [comment]
Added in dev version, will be available in next release
