### ISSUE TITLE
PowerFlow Card calculate incorrect SOC%

### ISSUE THREAD

**Issue by dieswarte** [britkat1980/giv_tcp#188]
I have 2 Hybrid inverters - the one has 2 batteries connected and the other one 1 battery (2 x 9.5 and 1 x 9.5). The SOC % in the powerflow card however calculates the wrong SOC %. For example at the moment the inverter with 2 batteries connected is at 59% (11.2 kWh) and the inverter with 1 battery connected is 100% (9.5 kWh). This should therefore be about 74%. The PowerFlow card however shows 80% as the combined % for the batteries which I presume it is taking the 60% + 100% / 2 to get the 80%. So it is looking at the SOC of the inverter %s rather than the kWh of the inverters when it is calculating that %. I see though that this is the same % that is reported in the GivEnergy Cloud portal, so looks like the first calculation mistake is there

**Comment by gcoan** [comment]
Is this an issue with how you have set up your powerflow card?

It's most likely configured to use the inverter SoC which the inverter calculates itself based upon its connected batteries.  Givtcp then just makes that inverter data available to home assistant / your powerflow card.
If you want to calculate the % a different way from how the inverter does then you can just create a custom template entity in HA and point the powerflow card to it
