### ISSUE TITLE
Battery SOC kWh should be a `measurement` class, not `total_increasing`

### ISSUE THREAD

**Issue by peter1rhodes** [britkat1980/giv_tcp#199]
I'm 99.9% certain this is a bug, because the code is clearly written to catch this sensor and make it a `measurement`, but instead it gets labelled `total_increasing`, which is definitely incorrect (the [docs ](https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes)are very clear). I'm quite sure this is a typo, and I think the original intention is clear in the code, but there is a `2` that should be a `1`.

[Here, in HA_Discovery.py](https://github.com/britkat1980/giv_tcp/blob/90f78b32060b7808a2a055cf29993219bf9d8f66/GivTCP/HA_Discovery.py#L142C1-L142C63), the line `  if "soc" in str(topic.split("/")[-2]).lower():` should be `  if "soc" in str(topic.split("/")[-1]).lower():`. 

This is related to issue #195 , and causes the following errors in the HA logs: 
`Entity sensor.givtcp[serial]_soc_kwh from integration mqtt has state class total_increasing, but its state is not strictly increasing.`

**Comment by britkat1980** [comment]
Thanks, incorporated change in upcoming Beta's ready for v3

**Comment by britkat1980** [comment]
available in current Beta builds
