### ISSUE TITLE
givtcp 10 attempts failure

### ISSUE THREAD

**Issue by brianainger** [britkat1980/giv_tcp#201]
hi,
many thanks i installed this as i was getting the 10 attempts message with givtcp
givtcp beta version worked first time.
just a quicky i have an aio and gateway
i see the aio but not the gateway
di i need to put the ip somewhere ?
thanks again

**Comment by gcoan** [comment]
I think you need to put the gateway ip into GivTCP not the AIO

**Comment by brianainger** [comment]
I tried that, same result
I installed Givtcp-beta and it worked straight away
Thanks
