### ISSUE TITLE
Giv-tcp beta

### ISSUE THREAD

**Issue by brianainger** [britkat1980/giv_tcp#203]
Hi
Im running this because giv-tcp just gave me the 10 attempts message. This however works.
I have an aio with gateway, but the solar fields do not register
![IMG_4457](https://github.com/user-attachments/assets/7a53f744-5aa1-4feb-9599-d6b0c9a0e5f3)
Any ideas?
I tried adding the gateway ip as inverter 2 but still the same
Thanks
Ps the web interface gives error 502 bad gateway
Thanks

**Comment by britkat1980** [comment]
Is that PV data from the AIO or Gateway?

**Comment by brianainger** [comment]
Thanks, yesterday it sorted itself out and is now reading correct, and the web interface is suddenly working tooThanksSent from my iPhoneOn 30 Jul 2024, at 17:49, britkat1980 ***@***.***> wrote:﻿
Is that PV data from the AIO or Gateway?
