### ISSUE TITLE
[Feature request] Separate off-peak/standard/peak rate support

### ISSUE THREAD

**Issue by poolski** [britkat1980/giv_tcp#210]
As it stands, GivTCP supports configuring a day and night rate, plus start/end times for each. 
There are likely some of us who are on Octopus Flux which has, essentially, 3 separate rates:
- Standard import/export rates (0500 - 1600)
- Peak import/export rates (1600 - 1900)
- Off-peak import/export rates (0200 - 0500)

Is there any scope for adding these, or is it likely to involve a bunch of work in wiring up Palm correctly and adding a whole bunch of new Maths™ to account for it?

**Comment by gcoan** [comment]
Personally I use the Octopus integration to get the right rate for the energy dashboard as the givtcp entities aren't much use.

If support was added for three rates for Octopus Flux, there'd then be requests for support for Cosy which has three sets of cheap rate periods. 

Try the Octopus Energy Integration
