### ISSUE TITLE
Can’t adjust DC discharge lower SOC limits in Home Assistant

### ISSUE THREAD

**Issue by PatrickJanssens** [britkat1980/giv_tcp#211]
I’m controlling my 5kW hybrid inverter using home assistant. I can control most inverter parameters with the GivTCP addon, including the DC discharge times. But I struggle to control the DC Discharge Lower SOC limits. I can read the parameters, and I get the sliders to adjust them, but this does not seem to change the parameters in the inverter.
(I can change the Lower SOC Limits using the givenergy cloud remote control dashboard, but want to automate it in home assistant). I also prefer not to adjust the battery % reserve limit, as is a parameter PredBat is using, so I would not be fully in control of that one.

Anyone has this issue or knows a fix for this?

I have a 5kW hybrid inverter (gen 3) with software version D0.309-A0.309

**Comment by britkat1980** [comment]
Do you get any errors in the logs, or just no change reported in HA (noting that the portal won’t reflect change unless you force it to update individual registers).
In other words how do you know it’s not working? I don’t have a Gen3 so I can’t test these controls.

**Comment by PatrickJanssens** [comment]
I don't see anything in the HA logbook or the log_inv_1.logxxx files in the givtcp file. The inverter is just not responding to the chance I make in HA/GivTCP. I'm aware the portal is not refreshing automatically. I did force the register to update in the portal. But it just doesn't change.

Note that if I change any of the charge SOCs in HA this works OK (with a small caveat that it wont accept 100% as a setting. Setting the target charge SOCs to 99% works, which then changes the setting in the portal to 100%).
These changes show up in the logbook and log in the givTCP file as follows:

> 2024-08-29 21:40:15,539 - write - [INFO] - Setting Charge Target to: 50
> 2024-08-29 21:40:29,299 - write - [INFO] - Setting Charge Target to: 100
> 2024-08-29 21:50:11,050 - write - [INFO] - Setting Charge Target 2 to: 50
> 2024-08-29 21:53:46,496 - write - [INFO] - Setting Charge Target 2 to: 100  _(but this request is rejected and reverts to the original setting)_
> 2024-08-29 21:58:44,581 - write - [INFO] - Setting Charge Target 2 to: 25
> 2024-08-29 21:59:08,702 - write - [INFO] - Setting Charge Target 2 to: 99 _(changes inverter setting to 100%)_

**Comment by britkat1980** [comment]
Ok, so Charge SOC works, but Discharge SOC doesn’t? Thats something more to go on. I’ll take a look and check I’ve got the right mapping in place

**Comment by britkat1980** [comment]
Can you try v3 and let me know if the issue still remains?

**Comment by PatrickJanssens** [comment]
Yes, seems to work now! The setting value responds immediately in HA and also changes in the GivTCP remote control page after refreshing the parameter.
Thanks for sorting this out!!
