### ISSUE TITLE
GivTCP Beta: Battery Topics Missing 

### ISSUE THREAD

**Issue by JonathanLew1s** [britkat1980/giv_tcp#212]
In 2.4.1 the MQTT output has entries for the battery serial topics under the battery details tree. 2.4.6* the battery serial topics move under the battery stack entry related to the inverter.

My MQTT battery devices in HA are based on the topics in the root of battery details, as a result post upgrade, to 2.4.6* there are no HA MQTT entities that are updated with individual battery data such as SOC or voltages
HA is not presenting the battery information nested under the HA battery stack device, and the 2.4.1 entities go unknown.

<img width="354" alt="image" src="https://github.com/user-attachments/assets/072aef70-0739-46eb-bc42-479bcd836b3c">
<img width="733" alt="image" src="https://github.com/user-attachments/assets/d1c5d9be-b28d-4e07-85bf-4f97f14711ee">
<img width="1504" alt="image" src="https://github.com/user-attachments/assets/b032a779-f7f5-44cb-a1df-740ef52e851a">
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/7a8eae48-1a47-442f-861b-5d941f9940f5">

**Comment by britkat1980** [comment]
In the MQTT broker delete all GivEnergy discovery topics under "homeassistant", then all the GivEnergy topics, then restart the addon.
This is due to the broken build pushed to Prod. V3 upgrade (when ready) will do this automatically for you.
