### ISSUE TITLE
Surge protection

### ISSUE THREAD

**Issue by Dash** [britkat1980/giv_tcp#217]
Bit of a speculative question.  I've got a AIO with a Gateway, the Gateway has a surge protection device that is connected to the logic board - my assumption is that this can be addressed and the status retrieved.  There is nothing corresponding in the GivEnergy portal, so I don't know this for a fact.

Is it possible to query this and provide information on its state?

**Comment by britkat1980** [comment]
I've reviewed the modbus protocol docs and its not clear to me if that info is exposed. theres some fault protection registers, but I don't have the mapping for what the numbers might mean. Unless GE can share if this is available (and if its not on the portal then I guess not), I can't really add it.
