### ISSUE TITLE
GivTCP Beta 2.4.741 Unpickling Error

### ISSUE THREAD

**Issue by jasonwfrancis1** [britkat1980/giv_tcp#219]
![IMG_0739](https://github.com/user-attachments/assets/325d9d3c-8f86-4b29-a79b-b7b279ab0957)

this has been happening frequently for the last few versions.

**Comment by jasonwfrancis1** [comment]
Inverter 1 is a gateway.

**Comment by britkat1980** [comment]
fixed in beta3.0.0b
