### ISSUE TITLE
GivTCP Beta 2.4.741 Unsupported Operand Type

### ISSUE THREAD

**Issue by jasonwfrancis1** [britkat1980/giv_tcp#220]
![IMG_0740](https://github.com/user-attachments/assets/eab1333a-7307-4d60-9bb7-4d49e609abd1)

**Comment by jasonwfrancis1** [comment]
Inverter 3 is an AIO

**Comment by jasonwfrancis1** [comment]
Same in 3.0.0a

![IMG_0745](https://github.com/user-attachments/assets/6e33aebb-1c74-4382-ac8f-8aa1bf10908f)

**Comment by britkat1980** [comment]
fixed in v3
