### ISSUE TITLE
Option 'HOSTIP' does not exist in the schema for GivTCP

### ISSUE THREAD

**Issue by holdestmade** [britkat1980/giv_tcp#222]
Getting these in my Supervisor logs every 5 minutes after updating Supervisor from 2024.08.0 to 2024.09.0

`2024-09-05 11:38:46.555 WARNING (MainThread) [supervisor.addons.options] Option 'HOSTIP' does not exist in the schema for GivTCP (a6a2857d_givtcp)`

Looked in UI config, there is no option but in the YAML config there is `HOSTIP: homeassistant.local` right at the bottom.

Do I need to delete that entry or change it to IP address ?

**Comment by britkat1980** [comment]
You can delete the entry if you want. It doesn't affect operation. With v3 release imminant this will be close as no applicable.
