### ISSUE TITLE
Lost access to battery with 3.0.3?

### ISSUE THREAD

**Issue by mprowe** [britkat1980/giv_tcp#248]
Following the bummpy transfer from 2.4.9 through 3.0.0 > 3.0.1 > 3.0.2 and now 3.0.3, I now see that I now no longer am able to "see" my battery? Not sure how to pass the information in text-form, so it will have to be screenshot (sorry).
![image](https://github.com/user-attachments/assets/4cff9a2b-d87c-4990-a488-31f2ded3868c)
Do I go back to 2.4.9? Or leave it alone until you advise on a solution?
Regards, Martin

**Comment by gcoan** [comment]
I had this happen on v3.0.0.  There is a fix @britkat1980 advised on deleting entities from MQTT and I believe it was going to be fixed in v3.0.1 however I have at present reverted back to v2.4.9 as that was working and stable for me.

It *might* work correctly if you downgrade to 2.4.9 and then upgrade directly to the latest patch to v3,  going via the interim releases may be why the fixes introduced in 3.0.1 didn't work for you.  That's a suggestion rather than evidence based though !!

**Comment by mprowe** [comment]
> however I have at present reverted back to v2.4.9 as that was working and stable for me.

Okay. I'm going to do the same. I'm afraid my skills are not up to poking around in the MQTT Server!

**Comment by britkat1980** [comment]
> Following the bummpy transfer from 2.4.9 through 3.0.0 > 3.0.1 > 3.0.2 and now 3.0.3, I now see that I now no longer am able to "see" my battery? Not sure how to pass the information in text-form, so it will have to be screenshot (sorry). ![image](https://private-user-images.githubusercontent.com/14279344/371414715-4cff9a2b-d87c-4990-a488-31f2ded3868c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTc3NTMsIm5iZiI6MTcyNzUxNzQ1MywicGF0aCI6Ii8xNDI3OTM0NC8zNzE0MTQ3MTUtNGNmZjlhMmItZDg3Yy00OTkwLWE0ODgtMzFmMmRlZDM4NjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDA5NTczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZDFmZTU5OTM4Mjc4NmVjMWNjYjUwMzViMjhiNDI3ODFiYTdlNzY5NjhlOTNlNzZjN2Y0MzRlZDU5ZDQxNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B7dMNmam9j2OnvzR8SfklhLycunLD2ovxHqhJGZFcOk) Do I go back to 2.4.9? Or leave it alone until you advise on a solution? Regards, Martin

The entity friendly names look odd, can you confirm via the MQTT integration pages that there aren't any other battery devices. You can delete them from that page, to save mucking around with an MQTT broker.
