### ISSUE TITLE
Incorrect GivTCP version reported in MQQT

### ISSUE THREAD

**Issue by drt102** [britkat1980/giv_tcp#249]
I'm 99% sure I am running v3.0.3 having pulled the latest release from Docker Hub but the GivTCP_Version reported via MQTT Explorer is 3.0.1.

**Comment by BrianUK6** [comment]
Agreed. same here.

**Comment by PhillWalker** [comment]
same here, fresh upgrade from 2.4.9 last night

**Comment by britkat1980** [comment]
Fixed in 3.0.4
