### ISSUE TITLE
Reported battery type keeps switching between lead-acid and lithium

### ISSUE THREAD

**Issue by jamesremuscat** [britkat1980/giv_tcp#266]
Since upgrading to v3.0.3 there's a new "battery type" sensor, but it's not very reliable:

![image](https://github.com/user-attachments/assets/72f7e8c1-e41a-4aaa-8d8d-f54969bd57ef)

The blue periods are when it decides to turn into a lead-acid battery, the purple is when lithium is (correctly) reported.

**Comment by britkat1980** [comment]
Fixed in 3.0.4
