### ISSUE TITLE
Battery SOC showing peaks well in excess of battery capacity

### ISSUE THREAD

**Issue by CaptSB** [britkat1980/giv_tcp#267]
![Screenshot 2024-10-05 103750](https://github.com/user-attachments/assets/ba491c5d-be1a-48b5-8f8d-37e3e9586b09)

I have only seen this since upgrading to GivTCP 3 - currently using 3.0.3.

Gen 1 Hybrid Inverter with 8.2kWh battery - Firmware rev 3017.

Latest HA running on latest HAOS on a Raspberry Pi 4 using MQTT

**Comment by britkat1980** [comment]
Fixed in 3.0.4
