### ISSUE TITLE
3.0.4 AIO Errors

### ISSUE THREAD

**Issue by jasonwfrancis1** [britkat1980/giv_tcp#271]
I get the following errors with 3.0.4, it’s happened 3 times. I have reverted back to 3.0.1 as it does not have these issues.

![Uploading IMG_0873.jpeg…]()

**Comment by jasonwfrancis1** [comment]
![Uploading IMG_0874.jpeg…]()

**Comment by jasonwfrancis1** [comment]
![IMG_0874](https://github.com/user-attachments/assets/68fa5f2e-2db6-4f56-b3be-49212fc7bb62)

**Comment by jasonwfrancis1** [comment]
![Uploading IMG_0875.jpeg…]()

**Comment by jasonwfrancis1** [comment]
This still happens in 3.0.5

![IMG_0883](https://github.com/user-attachments/assets/c70be73f-9f74-40d7-a096-b74c6c14d37e)

**Comment by britkat1980** [comment]
Fixed in 3.0.4 (production)
