### ISSUE TITLE
REST - readData raw contains unexpected text

### ISSUE THREAD

**Issue by springfall2008** [britkat1980/giv_tcp#302]
In the REST 'raw' read data there are quite a few fields which contain text which look like Python code, I think these should be values?

            "charge_slot_1": "TimeSlot(start=datetime.time(23, 0), end=datetime.time(5, 0))",
            "charge_slot_10": "TimeSlot(start=datetime.time(0, 0), end=datetime.time(0, 0))",

**Comment by britkat1980** [comment]
Raw output from the lib provides a timeslot object, would you prefer these to be converted to tuple of start and end time strings?

**Comment by britkat1980** [comment]
Dev 3.0.42+ has code to make all raw output string safe in the REST output
