### ISSUE TITLE
REST - setBatteryMode is incorrectly documented

### ISSUE THREAD

**Issue by springfall2008** [britkat1980/giv_tcp#39]
The readme says setBatteryMode has a numerical argument, but it actually takes a text string e.g. 'Eco'

 setBatteryMode          | Sets   battery operation mode. Mode value must be in the range 1-4                                                                                                                                        | /setBatteryMode          | {"mode":"1"}                                               | setBatteryMode          | 1

**Comment by britkat1980** [comment]
Scheduled for update in 2.1.14

**Comment by springfall2008** [comment]
Fixed
