### ISSUE TITLE
Exception("Garbage or failed Invertor Response: ERROR:-(<class 'KeyError'>, KeyError(HR:013)

### ISSUE THREAD

**Issue by stuartornum** [britkat1980/giv_tcp#40]
Hi,

I'm getting an error (log file at the bottom) when trying to pull data from a GEN1 3.6kW inverter. 

Worthy notes:

- Running latest v2.1.13, was using HA, however, running locally to debug as well
- Also have a GEN2 5kW, this works perfectly fine with GivTCP
- The GEN1 was working before with GivTCP, until a dodgy firmware update bricked the inverter
- A GivEnergy engineer came today to replace the GEN1 control board
- The GEN1 is now back online and reporting back to the GivEnergy Portal just fine
- The GEN1 does not have a battery attached (before, I noticed GivTCP would only work with `NUMBATTERIES_1=1` even though no battery was attached)
- Default config except for LOG_LEVEL=Debug

```- NUMINVERTORS=1
- INVERTOR_IP_1=192.168.10.16
- NUMBATTERIES_1=0
- MQTT_OUTPUT=False
- MQTT_ADDRESS=
- MQTT_USERNAME=
- MQTT_PASSWORD=
- HOSTIP=
- CACHELOCATION=/config/GivTCP
- TZ=Europe/London
```

GEN1 3.6kW Log: https://gist.github.com/stuartornum/d25677051bb5d6f201a3d8c84b91f1be

Thanks

**Comment by britkat1980** [comment]
That is a common error, and at this point has no fix. However it should only occur sporadically. Are you not receiving any data at all for this invertor?

**Comment by stuartornum** [comment]
> That is a common error, and at this point has no fix. However it should only occur sporadically. Are you not receiving any data at all for this invertor?

Thanks for the reply.

This happens continually, I've not managed to get any data out of this inverter since it's control board was changed.

Is this down to a specific firmware of the inverter?

Is there any debugging tasks I can do on my side to pinpoint where it's failing?

Thanks again

**Comment by britkat1980** [comment]
If you set Log-Level to debug and then send me the log output, that might help point it in the right direction. How are you running this, via HA Addon, or your own docker container?

**Comment by stuartornum** [comment]
https://gist.github.com/stuartornum/d25677051bb5d6f201a3d8c84b91f1be

It gets stuck in this loop.
Thanks,
