### ISSUE TITLE
Log rotation not deleting old log files

### ISSUE THREAD

**Issue by sOckhamSter** [britkat1980/giv_tcp#45]
Log rotation is working, but it's not adhering to the 7 historical file limit in the TimedRotatingFileHandler call (History = 7). It's keeping all previous versions of the log file.

**Comment by gcoan** [comment]
I have noticed the same issue, logfiles are not being removed by givtcp, I have one for every day I've been running GivTCP 
![image](https://github.com/britkat1980/giv_tcp/assets/142018870/65cfd8e5-ca25-43b8-bef7-7718c1880b88)
