### ISSUE TITLE
Octopus Flux support

### ISSUE THREAD

**Issue by mcmillanb** [britkat1980/giv_tcp#49]
The current config can’t handle the octopus flux tariff. Flux gives you 4 time periods (02:00-5:00,5:00-16:00,16:00-19:00 & 19:00 to 02:00). 
it also has 3 import prices and 3 export prices. 

https://octopus.energy/smart/flux/

GivTCP currently only supports 2 import and 1 export rates.

**Comment by springfall2008** [comment]
You might find this useful: https://github.com/springfall2008/batpred
