### ISSUE TITLE
Feature request - ability to read registers directly via REST API

### ISSUE THREAD

**Issue by springfall2008** [britkat1980/giv_tcp#56]
Currently via REST you can only force a entire refresh of the register set (runAll), but you can't read a particular register

Could we have it so that you can read a register directly?

Being able to write directly would also be nice, but I understand the risk of breaking stuff maybe too high.

**Comment by britkat1980** [comment]
The agreement with GE is not to allow unfettered register writing in GivTCP, its just too dangerous!

If there's anything you'd like to control, then I can look at adding it, if appropriate

**Comment by springfall2008** [comment]
I’d like to be able to read back a register value to check a write was successful. Right now I force a full refresh and the check the JSON data. I don’t think direct writes are required as such.

**Comment by springfall2008** [comment]
In terms of controls, I think the REST API has most stuff now, although there is something a bit odd with Eco mode where tries to change the reserve to a saved value. I'd prefer if the interface change one register at once and didn't depend at all on the GivTCP cache.
