### ISSUE TITLE
Eco(Paused) not working

### ISSUE THREAD

**Issue by Gary-Manuel** [britkat1980/giv_tcp#64]
I believe that Eco(Paused) just sets Battery Power Reserve to 100% in order to disable discharge. It would appear though, that 100% is not a valid setting for Battery Power Reserve, either from HA or from the portal. 99% is however a valid setting and it is suggested that GivTCP could use this instead of 100%.

**Comment by britkat1980** [comment]
I am able to set battery power reserve to 100% on my HY5.0, what model do you have and what f/w?

**Comment by Gary-Manuel** [comment]
Hi. Just checked again and it's the same. Can set to 99% but not 100% from both HA and the portal. Same on both inverters. 2 x HY3.6 Gen2 on v909 with a single 9.5kWh battery on each running v3012.
________________________________

**Comment by britkat1980** [comment]
Ok, perhaps this is a Gen2 thing? I’ll check with the GE team


Gary-Manuel   ***@***.*** ***@***.***)>   28 Jun 2023 at 20:12:29   wrote:
> Hi. Just checked again and it's the same. Can set to 99% but not 100% from both HA and the portal. Same on both inverters. 2 x HY3.6 Gen2 on v909 with a single 9.5kWh battery on each running v3012.
>   
________________________________
>   
From: britkat1980 ***@***.***>
>   
Sent: 28 June 2023 18:49
>   
To: britkat1980/giv_tcp ***@***.***>
>   
Cc: Gary-Manuel ***@***.***>; Author ***@***.***>
>   
Subject: Re: [britkat1980/giv_tcp] Eco(Paused) not working (Issue #64)
>
>
>   
I am able to set battery power reserve to 100% on my HY5.0, what model do you have and what f/w?

**Comment by Gary-Manuel** [comment]
Thank you.
________________________________
