### ISSUE TITLE
Battery Power missing battery to grid

### ISSUE THREAD

**Issue by adamwylde** [britkat1980/giv_tcp#71]
Perhaps I'm misunderstanding what the various outputs in GivTcp mean, but the 'battery power' seems to reflect a positive/negative flow of power into/out of the battery (regardless of where its going)? However I find that it does not include exporting to the grid?

I'm trying to use that (perhaps incorrectly) as a guage in Home Assistant but when exporting it sits relatively idle whilst 'battery to grid' is registering the export:

![image](https://github.com/britkat1980/giv_tcp/assets/39195357/92e19b5d-4d5a-43a2-9a3e-42d48e5b4210)

**Comment by adamwylde** [comment]
Restarting GivTCP seems to have resolved this for now and the figures now make sense, although this is not the first time I've seen it happen.

![image](https://github.com/britkat1980/giv_tcp/assets/39195357/f8d45e4f-7099-4483-adf2-e83f41fb79e8)

**Comment by britkat1980** [comment]
The power flow stats (XX to XX) are derived values and as such are not always consistent, depending on sampling values. I tend not to rely too heavily on them
