### ISSUE TITLE
Export rate set in Config does not update sensor

### ISSUE THREAD

**Issue by newmancp** [britkat1980/giv_tcp#80]
Changes to the Export rate set within the Config does not change the value in the sensor, export_rate_2. Constantly reads 0.04.

Cheers, Chris

**Comment by britkat1980** [comment]
The sensor should not have the "_2" present, can you confirm if this is an old legacy entity or a current one?

**Comment by newmancp** [comment]
Hi, all of my sensors have _2 after them. I thought the _2 were the updated entities? Chris

**Comment by britkat1980** [comment]
Found the problem, and fixed in 2.3.0
