### ISSUE TITLE
It is possible to attempt to set target_soc to 0%, which is then ignored as it is below the minimum threshold

### ISSUE THREAD

**Issue by danhogwood** [britkat1980/giv_tcp#81]
To recreate this:

Slide the target_soc to 0% and nothing happens

What I would expect:

The target_soc should be set to the minimum valid value (eg 4%)

Alternatively:

It should not be possible to slide the target_soc to lower than the valid minimum

**Comment by britkat1980** [comment]
Changed behaviour to force value of 4 if set lower (and 100 if set higher). Expected release: 2.3.0
